### ISSUE TITLE
auctions undefined error

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-sdk#31]
Related to #18 

Still seeing this error, eg in RETH collateral auction

```
index.tsx:125 TypeError: Cannot read properties of undefined (reading 'toString')
    at auctions.ts:102:44
```

**Comment by jahabeebs** [comment]
@pi0neerpat v1.5.8-rc.4 doesn't have the code that I had written to fix this issue. Would you mind bumping the SDK version with the dev branch code and we can try it?

Here's the PR that should have fixed the issue: https://github.com/open-dollar/od-sdk/pull/30/files

Here's the relevant file in v1.5.8-rc.4 that doesn't have the fix: https://github.com/open-dollar/od-sdk/blob/v1.5.8-rc.4/src/auctions/auctions.ts

and here's the file in dev branch that has the fix: https://github.com/open-dollar/od-sdk/blob/dev/src/auctions/auctions.ts

**Comment by pi0neerpat** [comment]
Thanks this is on my todo list

**Comment by pi0neerpat** [comment]
@jahabeebs will use the gh action publish a new version.
- verify versioning is correct v1.5.8-rcX
- Update the sdk in the app

**Comment by jahabeebs** [comment]
> @jahabeebs will use the gh action publish a new version.
> 
>     * verify versioning is correct v1.5.8-rcX
> 
>     * Update the sdk in the app

@pi0neerpat So it turns out when you updated the SDK to rc.5 in early December it included my latest code in dev, which fixes the auction issue. I figured this out because when I ran the publish action it always skipped because there was nothing to include in the changelog (https://github.com/open-dollar/od-sdk/actions/runs/7340204345/job/19985813080). We can close this issue because RETH auctions are working in the testnet app

<img width="1116" alt="Screenshot 2023-12-27 at 11 55 42 AM" src="https://github.com/open-dollar/od-sdk/assets/47253537/c4948ca1-36ab-4288-bc7c-9f058a2b7023">
