### ISSUE TITLE
Remove duplicate definition warning

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-sdk#5]
How can we remove all these console logs from the sdk?

```
Duplicate definition of ModifyParameters (ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,bytes32,uint256))
Duplicate definition of ModifyParameters (ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,address))
Duplicate definition of ModifyParameters (ModifyParameters(bytes32,bytes32,uint256), ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,address), ModifyParameters(bytes32,uint256,uint256), ModifyParameters(bytes32,uint256,uint256,address))
Duplicate definition of ModifyParameters (ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,address), ModifyParameters(bytes32,bytes32,uint256), ModifyParameters(bytes32,bytes32,address))
```

**Comment by jahabeebs** [comment]
> How can we remove all these console logs from the sdk?
> 
> ```
> Duplicate definition of ModifyParameters (ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,bytes32,uint256))
> Duplicate definition of ModifyParameters (ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,address))
> Duplicate definition of ModifyParameters (ModifyParameters(bytes32,bytes32,uint256), ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,address), ModifyParameters(bytes32,uint256,uint256), ModifyParameters(bytes32,uint256,uint256,address))
> Duplicate definition of ModifyParameters (ModifyParameters(bytes32,uint256), ModifyParameters(bytes32,address), ModifyParameters(bytes32,bytes32,uint256), ModifyParameters(bytes32,bytes32,address))
> ```

@pi0neerpat 

This specific log can't be turned off in ethers 5 so we have a couple of options:

1) only allow ethers logging in dev and not in prod (I think this might be best since we still need ethers logging for debugging in dev)
2) turn off ethers logging for dev and prod
3) migrate ethers to v6 (would require refactoring of how we use BigNumbers and providers in the SDK--see here: https://docs.ethers.org/v6/migrating/) 

related issues:
https://github.com/ethers-io/ethers.js/issues/1029
https://github.com/Midas-Protocol/monorepo/issues/1126

**Comment by pi0neerpat** [comment]
Closing for now. Not high enough priority to continue
