### ISSUE TITLE
Hide warnings for duplicate definition

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-sdk#60]
Remove the warnings for

```
Duplicate definition of TransferCollateral (TransferCollateral(address,uint256,address,uint256), TransferCollateral(address,bytes32,uint256,address,uint256))
```

**Comment by jahabeebs** [comment]
@pi0neerpat It seems this is a duplicate of https://github.com/open-dollar/od-sdk/issues/5

If you want these to be turned off which option listed in the previous issue do you think is best?

 If we go with updating our app & SDK to ethers v6 then it will require refactoring everywhere we use ethers.utils or BigNumber which is fine, however upgrading may break our wallet switching logic because web3-react is using ethers v5 (see https://github.com/Uniswap/web3-react/issues/812)

**Comment by pi0neerpat** [comment]
Option to trim down ABI would require modifying our /abis package. Will ignore for now https://github.com/ethers-io/ethers.js/issues/1029
